service: mobile-eats-test
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-1
  memorySize: 512

functions:
  search:
    handler: handler.search
    events:
     - http:
         path: foodtrucks/search
         method: get
         request:
            parameters:
              querystrings:
                location: true
              headers:
                Authorization: true
  business:
    handler: handler.business
    events:
     - http:
         path: foodtrucks/{id}
         method: get
         request:
            parameters:
              querystrings:
                locale: false
              headers:
                Authorization: true
  auth:
    handler: handler.auth
    events:
      - http:
          path: foodtrucks/auth
          method: post